spring:
    application:
            name: ratail-amount
    datasource:
        url: jdbc:mysql://localhost:3306/retail
        username: root
        password: 123456
server:
  port: 10002
---
spring:
  profiles: sit
  datasource:
      url: jdbc:mysql://localhost:3306/retail
      username: futureretail
      password: futureretail