spring:
    application:
            name: ratail-amount
    datasource:
        url: jdbc:mysql://54.255.182.198:3306/retail
        username: retail
        password: retail__123
server:
  port: 10002
---
spring:
  profiles: sit
  datasource:
      url: jdbc:mysql://54.255.182.198:3306/retail
      username: retail
      password: retail__123