spring:
    application:
        name: ratail-commodity
    jpa:
        hibernate:
          ddl-auto: create
    datasource:
        url: jdbc:mysql://localhost:3306/retail_stock
        username: root
        password: 123456
server:
    port: 9001
