spring:
    application:
        name: ratail-stock
    jpa:
        hibernate:
          ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/retail_stock
        username: root
        password:
server:
    port: 9001

