spring:
    application:
        name: ratail-commodity
server:
  port: 9001
---
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://localhost:3306/retail_stock
      username: root
      password: 123456

